### ISSUE TITLE
Problem with Rscript NovelExonicNonSynSNPs.R

### ISSUE THREAD

**Issue by flashton2003** [shashidhar22/NeST#7]
Hello, me again! :-)

I'm testing NeST with some data from SRA but it's failing to run NovelExonicNonSynSNPs.R

Terminal output is below:

```
(nest) ubuntu@nhien-malaria:~$ python3 ~/programs/NeST/nest.py -i public_data/fastqs/ -a programs/NeST/ref/pfalciparum/adapters.fa -r programs/NeST/ref/pfalciparum/mdr.fa -o public_data/output/ -b programs/NeST/ref/pfalciparum/mdr.bed -m bowtie2 --varofint programs/NeST/ref/pfalciparum/Reportable_SNPs.csv
2019-01-25 06:43:10,348 - NeST - INFO - Gathering input information from input path.
2019-01-25 06:43:10,361 - NeST.prepInputs - INFO - A total of 1 libraries were identified from the given folder /home/ubuntu/public_data/fastqs
2019-01-25 06:43:10,361 - NeST - INFO - Running MaRS on 1 experiments
2019-01-25 06:43:21,007 - NeST.SRR7853847 - INFO - Total variants : 5; Verified calls : 5; Exonic : 5; Intronic : 0; Synonymous : 1; Non Synonymous : 4; Transition : 2; Transversion : 3
2019-01-25 06:43:21,008 - NeST - INFO - Summarizing variant calls from all 1 experiments
2019-01-25 06:43:21,942 - NeST.Summary - INFO - Plotting Depth Per SNP
2019-01-25 06:43:28,986 - NeST.Summary - INFO - Plotting Reportable SNPs Frequency
2019-01-25 06:43:30,239 - NeST.Summary - INFO - Plotting Novel Exonic Non-Synonymous SNPs
2019-01-25 06:43:31,555 - NeST.Summary - ERROR - Failed to execute NovelExonicNonSynSNPs.R
2019-01-25 06:43:31,556 - NeST.Summary - ERROR - Rscript /home/ubuntu/programs/NeST/nest/Rscripts/NovelExonicNonSynSNPs.R -i public_data/output//Reports/Study_novel_exonic_variants.csv -o public_data/output//Figures/
2019-01-25 06:43:31,556 - NeST.Summary - INFO - Plotting Novel Exonic Synonymous SNPs
2019-01-25 06:43:32,985 - NeST.Summary - ERROR - Failed to execute NovelExonicSynSNPs.R
2019-01-25 06:43:32,986 - NeST.Summary - ERROR - Rscript /home/ubuntu/programs/NeST/nest/Rscripts/reportableSNPsFreq.R -i public_data/output//Reports/Study_known_variants.csv -r programs/NeST/ref/pfalciparum/Reportable_SNPs.csv -o public_data/output//Figures/
2019-01-25 06:43:32,986 - NeST.Summary - INFO - Plotting Novel Intronic SNPs
2019-01-25 06:43:33,818 - NeST.Summary - ERROR - Failed to execute NovelIntronicSNPs.R
2019-01-25 06:43:33,818 - NeST.Summary - ERROR - Rscript /home/ubuntu/programs/NeST/nest/Rscripts/NovelIntronicSNPs.R -i public_data/output//Reports/Study_novel_intronic_variants.csv -o public_data/output//Figures/
Traceback (most recent call last):
  File "/home/ubuntu/programs/NeST/nest.py", line 451, in <module>
    args.pic_path, args.voi_path, java_def, sra_def, args.verbose)
  File "/home/ubuntu/programs/NeST/nest.py", line 373, in marsBatch
    summary.getSummary()
  File "/home/ubuntu/programs/NeST/nest/summarize.py", line 753, in getSummary
    os.remove('{0}/novel_SNPs_intronic.csv'.format(fig_path))
FileNotFoundError: [Errno 2] No such file or directory: 'public_data/output//Figures/novel_SNPs_intronic.csv'
```

When I try to run the Rscript just by itself, I get this output

```
(nest) ubuntu@nhien-malaria:~$ Rscript /home/ubuntu/programs/NeST/nest/Rscripts/NovelExonicNonSynSNPs.R -i public_data/output/Reports/Study_novel_exonic_variants.csv -o public_data/output/Figures/

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Parsed with column specification:
cols(
  Sample = col_character(),
  Variant = col_character(),
  Chrom = col_character(),
  Gene = col_character(),
  Ref = col_character(),
  Alt = col_logical(),
  Pos = col_integer(),
  Qual = col_double(),
  RefCodon = col_character(),
  RefAA = col_character(),
  AltCodon = col_character(),
  AltAA = col_character(),
  AAPos = col_integer(),
  Exon = col_character(),
  AF = col_double(),
  DP = col_integer(),
  Conf = col_integer()
)
Parsed with column specification:
cols(
  Sample = col_character(),
  Variant = col_character(),
  Chrom = col_character(),
  Gene = col_character(),
  Ref = col_character(),
  Alt = col_logical(),
  Pos = col_integer(),
  Qual = col_double(),
  RefCodon = col_character(),
  RefAA = col_character(),
  AltCodon = col_character(),
  AltAA = col_character(),
  AAPos = col_integer(),
  Exon = col_character(),
  AF = col_integer(),
  DP = col_integer(),
  Conf = col_integer()
)
Parsed with column specification:
cols(
  gene = col_character(),
  `AAPos=` = col_character(),
  `RefAA=` = col_character(),
  `AltAA=` = col_character(),
  name = col_character()
)
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 0, 1
Calls: cbind -> cbind -> data.frame
Execution halted
```

Just in case it's useful, here are the files which NeST makes in the output dir

```
(nest) ubuntu@nhien-malaria:~$ tree public_data/output/
├── Figures
│   ├── novel_SNPs_exonic_nonsyn.csv
│   ├── Novel_SNPs_exonic_syn.pdf
│   ├── Novel_SNPs_Report_exonic_syn.csv
│   ├── Reportable_SNPs.pdf
│   ├── Reportable_SNPs_Report.csv
│   ├── Study_depth.pdf
│   └── Study_novel_exonic_variants_filtered.csv
├── nest.log
├── Reports
│   ├── Study_known_variants_allele_frequency.csv
│   ├── Study_known_variants.csv
│   ├── Study_known_variants_depth.csv
│   ├── Study_novel_exonic_variants.csv
│   ├── Study_novel_variants_allele_frequency.csv
│   └── Study_novel_variants_depth.csv
├── SRR7853847
│   ├── alignments
│   │   ├── output_FM.bam
│   │   ├── output_FM_SR.bam
│   │   ├── output_FM_SR_DD.bam
│   │   ├── output_FM_SR_DD_RG.bai
│   │   ├── output_FM_SR_DD_RG.bam
│   │   └── output.sam
│   ├── CleanedFastq
│   │   ├── SRR7853847_1.fastq_cleaned.fq
│   │   ├── SRR7853847_2.fastq_cleaned.fq
│   │   └── SRR7853847_2.fastq_stats.txt
│   ├── completion
│   │   ├── align.rt
│   │   ├── bbduk.rt
│   │   ├── bcfcall.rt
│   │   ├── bcfindex.rt
│   │   ├── dedup.rt
│   │   ├── fixmate.rt
│   │   ├── gatk.rt
│   │   ├── pileup.rt
│   │   ├── readgroup.rt
│   │   └── sort.rt
│   ├── mod_fasta.fa
│   ├── SRR7853847_variants.bcf
│   ├── SRR7853847_variants.bcf.csi
│   ├── SRR7853847_variants_gatk_annotated.vcf
│   ├── SRR7853847_variants_gatk.vcf
│   ├── SRR7853847_variants_gatk.vcf.idx
│   ├── SRR7853847_variants_merged_annotated.vcf
│   ├── SRR7853847_variants_samtools_annotated.vcf
│   └── SRR7853847_variants_samtools.vcf
└── Study_variants.json
```

And their sizes

```
(nest) ubuntu@nhien-malaria:~$ ls -lh public_data/output/*/*
-rw-rw-r-- 1 ubuntu ubuntu   31 Jan 25 06:49 public_data/output/Figures/novel_SNPs_exonic_nonsyn.csv
-rw-rw-r-- 1 ubuntu ubuntu 3.6K Jan 25 06:44 public_data/output/Figures/Novel_SNPs_exonic_syn.pdf
-rw-rw-r-- 1 ubuntu ubuntu  129 Jan 25 06:44 public_data/output/Figures/Novel_SNPs_Report_exonic_syn.csv
-rw-rw-r-- 1 ubuntu ubuntu 5.7K Jan 25 06:44 public_data/output/Figures/Reportable_SNPs.pdf
-rw-rw-r-- 1 ubuntu ubuntu 2.9K Jan 25 06:44 public_data/output/Figures/Reportable_SNPs_Report.csv
-rw-rw-r-- 1 ubuntu ubuntu 8.2K Jan 25 06:44 public_data/output/Figures/Study_depth.pdf
-rw-rw-r-- 1 ubuntu ubuntu  183 Jan 25 06:49 public_data/output/Figures/Study_novel_exonic_variants_filtered.csv
-rw-rw-r-- 1 ubuntu ubuntu  727 Jan 25 06:43 public_data/output/Reports/Study_known_variants_allele_frequency.csv
-rw-rw-r-- 1 ubuntu ubuntu 3.8K Jan 25 06:43 public_data/output/Reports/Study_known_variants.csv
-rw-rw-r-- 1 ubuntu ubuntu  787 Jan 25 06:43 public_data/output/Reports/Study_known_variants_depth.csv
-rw-rw-r-- 1 ubuntu ubuntu  182 Jan 25 06:43 public_data/output/Reports/Study_novel_exonic_variants.csv
-rw-rw-r-- 1 ubuntu ubuntu   38 Jan 25 06:43 public_data/output/Reports/Study_novel_variants_allele_frequency.csv
-rw-rw-r-- 1 ubuntu ubuntu   35 Jan 25 06:43 public_data/output/Reports/Study_novel_variants_depth.csv
-rw-rw-r-- 1 ubuntu ubuntu  20K Jan 25 06:43 public_data/output/SRR7853847/mod_fasta.fa
-rw-rw-r-- 1 ubuntu ubuntu  90K Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants.bcf
-rw-rw-r-- 1 ubuntu ubuntu  182 Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants.bcf.csi
-rw-rw-r-- 1 ubuntu ubuntu 9.9K Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants_gatk_annotated.vcf
-rw-rw-r-- 1 ubuntu ubuntu 8.2K Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants_gatk.vcf
-rw-rw-r-- 1 ubuntu ubuntu  395 Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants_gatk.vcf.idx
-rw-rw-r-- 1 ubuntu ubuntu  12K Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants_merged_annotated.vcf
-rw-rw-r-- 1 ubuntu ubuntu 5.2K Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants_samtools_annotated.vcf
-rw-rw-r-- 1 ubuntu ubuntu 3.5K Jan 25 06:43 public_data/output/SRR7853847/SRR7853847_variants_samtools.vcf

public_data/output/SRR7853847/alignments:
total 7.2M
-rw-rw-r-- 1 ubuntu ubuntu 931K Jan 25 06:43 output_FM.bam
-rw-rw-r-- 1 ubuntu ubuntu 907K Jan 25 06:43 output_FM_SR.bam
-rw-rw-r-- 1 ubuntu ubuntu 906K Jan 25 06:43 output_FM_SR_DD.bam
-rw-rw-r-- 1 ubuntu ubuntu  496 Jan 25 06:43 output_FM_SR_DD_RG.bai
-rw-rw-r-- 1 ubuntu ubuntu 899K Jan 25 06:43 output_FM_SR_DD_RG.bam
-rw-rw-r-- 1 ubuntu ubuntu 3.6M Jan 25 06:43 output.sam

public_data/output/SRR7853847/CleanedFastq:
total 3.5M
-rw-rw-r-- 1 ubuntu ubuntu 1.9M Jan 25 06:43 SRR7853847_1.fastq_cleaned.fq
-rw-rw-r-- 1 ubuntu ubuntu 1.7M Jan 25 06:43 SRR7853847_2.fastq_cleaned.fq
-rw-rw-r-- 1 ubuntu ubuntu  254 Jan 25 06:43 SRR7853847_2.fastq_stats.txt

public_data/output/SRR7853847/completion:
total 0
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 align.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 bbduk.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 bcfcall.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 bcfindex.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 dedup.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 fixmate.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 gatk.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 pileup.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 readgroup.rt
-rw-rw-r-- 1 ubuntu ubuntu 0 Jan 25 06:43 sort.rt
```

**Comment by shashidhar22** [comment]
Thanks for bringing the issue to notice, it is happening because there is only one novel exonic synonymous variants, and no non-synonymous or intronic variants. Whenever the plotting script has a returncode other than 0, it will just log an error message. But in the latest commit, I have changed that to a warning indicating that it is only because there was no variants found in that category.
